-- =============================================================
-- SCRIPT COMPLETO - BDFarmacia
-- SQL Server 2022
-- Versión 2.1 unificada (Presentación limpia + Cantidad/Unidad en SKU)
-- =============================================================

USE BDFarmacia
GO

-- =============================================================
-- SECCIÓN 0: LIMPIEZA (orden inverso de dependencias)
-- =============================================================

-- Módulo Abastecimiento
IF OBJECT_ID('DETALLE_RECEPCION',    'U') IS NOT NULL DROP TABLE DETALLE_RECEPCION
IF OBJECT_ID('RECEPCION_COMPRA',     'U') IS NOT NULL DROP TABLE RECEPCION_COMPRA
IF OBJECT_ID('DETALLE_ORDEN_COMPRA', 'U') IS NOT NULL DROP TABLE DETALLE_ORDEN_COMPRA
IF OBJECT_ID('ORDEN_COMPRA',         'U') IS NOT NULL DROP TABLE ORDEN_COMPRA
IF OBJECT_ID('CONTACTO_PROVEEDOR',   'U') IS NOT NULL DROP TABLE CONTACTO_PROVEEDOR
IF OBJECT_ID('PROVEEDOR',            'U') IS NOT NULL DROP TABLE PROVEEDOR

-- Módulo Devoluciones
IF OBJECT_ID('DETALLE_CAMBIO',       'U') IS NOT NULL DROP TABLE DETALLE_CAMBIO
IF OBJECT_ID('CAMBIO_PRODUCTO',      'U') IS NOT NULL DROP TABLE CAMBIO_PRODUCTO
IF OBJECT_ID('NOTA_CREDITO',         'U') IS NOT NULL DROP TABLE NOTA_CREDITO
IF OBJECT_ID('DEVOLUCION',           'U') IS NOT NULL DROP TABLE DEVOLUCION

-- Módulo Ventas
IF OBJECT_ID('COMPROBANTEVENTA',     'U') IS NOT NULL DROP TABLE COMPROBANTEVENTA
IF OBJECT_ID('DETALLE_VENTA',        'U') IS NOT NULL DROP TABLE DETALLE_VENTA
IF OBJECT_ID('LOTE',                 'U') IS NOT NULL DROP TABLE LOTE
IF OBJECT_ID('VENTA',                'U') IS NOT NULL DROP TABLE VENTA
IF OBJECT_ID('MEDIO_PAGO',           'U') IS NOT NULL DROP TABLE MEDIO_PAGO

-- Módulo Clientes / Usuarios
IF OBJECT_ID('USUARIO',              'U') IS NOT NULL DROP TABLE USUARIO
IF OBJECT_ID('CLIENTE',              'U') IS NOT NULL DROP TABLE CLIENTE

-- Módulo Productos
IF OBJECT_ID('DETALLE_PRODUCTO',     'U') IS NOT NULL DROP TABLE DETALLE_PRODUCTO
IF OBJECT_ID('MARCA',                'U') IS NOT NULL DROP TABLE MARCA
IF OBJECT_ID('LABORATORIO',          'U') IS NOT NULL DROP TABLE LABORATORIO
IF OBJECT_ID('PRESENTACION',         'U') IS NOT NULL DROP TABLE PRESENTACION
IF OBJECT_ID('PRODUCTO',             'U') IS NOT NULL DROP TABLE PRODUCTO
GO

-- =============================================================
-- SECCIÓN 1: MÓDULO PRODUCTOS
-- =============================================================

CREATE TABLE PRODUCTO (
    IDPRODUCTO  INT          IDENTITY(1,1) NOT NULL,
    NOMBRE      VARCHAR(255) NOT NULL,
    ESTADO      BIT          NOT NULL,
    DESCRIPCION VARCHAR(255) NOT NULL,

    CONSTRAINT PK_PRODUCTO PRIMARY KEY (IDPRODUCTO),
    CONSTRAINT UQ_PRODUCTO_NOMBRE UNIQUE (NOMBRE)
)
GO

-- Presentación ahora es un catálogo limpio (ej. "Caja", "Blíster")
CREATE TABLE PRESENTACION (
    IDPRESENTACION   INT         IDENTITY(1,1) NOT NULL,
    TIPOPRESENTACION VARCHAR(50) NOT NULL,
    ESTADO           BIT         NOT NULL,

    CONSTRAINT PK_PRESENTACION PRIMARY KEY (IDPRESENTACION),
    CONSTRAINT UQ_PRESENTACION UNIQUE (TIPOPRESENTACION)
)
GO

CREATE TABLE LABORATORIO (
    IDLABORATORIO    INT          IDENTITY(1,1) NOT NULL,
    NOMBRELABORATORIO VARCHAR(100) NOT NULL,
    DIRECCION        VARCHAR(150),
    TELEFONO         CHAR(9),
    VIGENCIA         BIT          NOT NULL,

    CONSTRAINT PK_LABORATORIO PRIMARY KEY (IDLABORATORIO),
    CONSTRAINT UQ_LABORATORIO_NOMBRE   UNIQUE (NOMBRELABORATORIO),
    CONSTRAINT UQ_LABORATORIO_DIRECCION UNIQUE (DIRECCION)
)
GO

CREATE TABLE MARCA (
    IDMARCA       INT         IDENTITY(1,1) NOT NULL,
    NOMBREMARCA   VARCHAR(50) NOT NULL,
    DESCRIPCION   TEXT,
    VIGENCIA      BIT         NOT NULL,
    IDLABORATORIO INT         NOT NULL,

    CONSTRAINT PK_MARCA PRIMARY KEY (IDMARCA),
    CONSTRAINT UQ_MARCA_NOMBRE UNIQUE (NOMBREMARCA),
    CONSTRAINT FK_MARCA_LABORATORIO
        FOREIGN KEY (IDLABORATORIO) REFERENCES LABORATORIO(IDLABORATORIO)
)
GO

-- Cantidad y Unidad se integran en el SKU
CREATE TABLE DETALLE_PRODUCTO (
    IDDETALLEPRODUCTO INT           IDENTITY(1,1) NOT NULL,
    SKU               VARCHAR(50)   NULL,
    PRECIO            DECIMAL(10,2) NOT NULL,
    ESTADO            BIT           NOT NULL,
    STOCK             INT           NOT NULL,
    CANTIDAD          INT           NOT NULL DEFAULT 1,
    UNIDAD            VARCHAR(20)   NOT NULL DEFAULT 'Unidad',
    IDMARCA           INT           NOT NULL,
    IDPRESENTACION    INT           NOT NULL,
    IDPRODUCTO        INT           NOT NULL,

    CONSTRAINT PK_DETALLE_PRODUCTO PRIMARY KEY (IDDETALLEPRODUCTO),
    CONSTRAINT UQ_DETALLE_PRODUCTO_SKU UNIQUE (SKU),
    CONSTRAINT UQ_DETALLE_PRODUCTO
        UNIQUE (IDMARCA, IDPRESENTACION, IDPRODUCTO, CANTIDAD, UNIDAD),
    CONSTRAINT FK_DETALLE_MARCA
        FOREIGN KEY (IDMARCA)        REFERENCES MARCA(IDMARCA),
    CONSTRAINT FK_DETALLE_PRESENTACION
        FOREIGN KEY (IDPRESENTACION) REFERENCES PRESENTACION(IDPRESENTACION),
    CONSTRAINT FK_DETALLE_PRODUCTO
        FOREIGN KEY (IDPRODUCTO)     REFERENCES PRODUCTO(IDPRODUCTO),
    CONSTRAINT CK_DETALLE_PRECIO
        CHECK (PRECIO > 0),
    CONSTRAINT CK_DETALLE_STOCK
        CHECK (STOCK >= 0),
    CONSTRAINT CK_DETALLE_CANTIDAD 
        CHECK (CANTIDAD > 0)
)
GO

-- =============================================================
-- SECCIÓN 2: MÓDULO CLIENTES Y USUARIOS
-- =============================================================

CREATE TABLE CLIENTE (
    IDCLIENTE       INT          IDENTITY(1,1) NOT NULL,
    TIPODOC         VARCHAR(20)  NOT NULL,
    NRODOC          VARCHAR(25)  NOT NULL,
    TIPO_CLIENTE    VARCHAR(10)  NOT NULL,
    NOMBRES         VARCHAR(100),
    APELLIDOPATERNO VARCHAR(50),
    APELLIDOMATERNO VARCHAR(50),
    RAZONSOCIAL     VARCHAR(150),
    DIRECCION       VARCHAR(150),
    TELEFONO        CHAR(9),
    CORREO          VARCHAR(100),

    CONSTRAINT PK_CLIENTE PRIMARY KEY (IDCLIENTE),
    CONSTRAINT UQ_CLIENTE_NRODOC UNIQUE (NRODOC),
    CONSTRAINT CK_CLIENTE_TIPO
        CHECK (TIPO_CLIENTE IN ('Natural', 'Juridico'))
)
GO

CREATE TABLE USUARIO (
    IDUSUARIO       INT          IDENTITY(1,1) NOT NULL,
    DNI             VARCHAR(8)   NOT NULL,
    NOMBRE          VARCHAR(100) NOT NULL,
    APELLIDOPATERNO VARCHAR(50)  NOT NULL,
    APELLIDOMATERNO VARCHAR(50)  NOT NULL,
    CORREO          VARCHAR(100) NOT NULL,
    TELEFONO        CHAR(9),
    FECHANACIMIENTO DATE         NOT NULL,
    DIRECCION       VARCHAR(150),
    SEXO            CHAR(1),
    CARGO           VARCHAR(100) NOT NULL,
    USUARIO         VARCHAR(50)  NOT NULL,
    CLAVE           VARCHAR(100) NOT NULL,
    ESTADO          BIT          NOT NULL,
    PREGUNTA        VARCHAR(100) NOT NULL,
    RESPUESTA       VARCHAR(100) NOT NULL,

    CONSTRAINT PK_USUARIO PRIMARY KEY (IDUSUARIO),
    CONSTRAINT UQ_USUARIO_DNI     UNIQUE (DNI),
    CONSTRAINT UQ_USUARIO_USUARIO UNIQUE (USUARIO),
    CONSTRAINT CK_USUARIO_SEXO    CHECK (SEXO IN ('M', 'F'))
)
GO

-- =============================================================
-- SECCIÓN 3: MÓDULO VENTAS Y LOTES
-- =============================================================

CREATE TABLE MEDIO_PAGO (
    IDMEDIOPAGO INT         IDENTITY(1,1) NOT NULL,
    NOMBRE      VARCHAR(50) NOT NULL,
    ESTADO      BIT         NOT NULL DEFAULT 1,

    CONSTRAINT PK_MEDIO_PAGO   PRIMARY KEY (IDMEDIOPAGO),
    CONSTRAINT UQ_MEDIO_NOMBRE UNIQUE (NOMBRE)
)
GO

CREATE TABLE VENTA (
    IDPEDIDO    INT      IDENTITY(1,1) NOT NULL,
    FECHAHORA   DATETIME NOT NULL,
    ESTADO      BIT      NOT NULL,
    IDUSUARIO   INT      NOT NULL,
    IDCLIENTE   INT      NOT NULL,
    IDMEDIOPAGO INT      NOT NULL,

    CONSTRAINT PK_VENTA PRIMARY KEY (IDPEDIDO),
    CONSTRAINT FK_VENTA_USUARIO
        FOREIGN KEY (IDUSUARIO)   REFERENCES USUARIO(IDUSUARIO),
    CONSTRAINT FK_VENTA_CLIENTE
        FOREIGN KEY (IDCLIENTE)   REFERENCES CLIENTE(IDCLIENTE),
    CONSTRAINT FK_VENTA_MEDIOPAGO
        FOREIGN KEY (IDMEDIOPAGO) REFERENCES MEDIO_PAGO(IDMEDIOPAGO)
)
GO

CREATE TABLE LOTE (
    IDLOTE            INT         IDENTITY(1,1) NOT NULL,
    NROLOTE           VARCHAR(50) NOT NULL,
    FECHAVENCIMIENTO  DATE        NOT NULL,
    STOCK_INICIAL     INT         NOT NULL DEFAULT 0,
    STOCK_ACTUAL      INT         NOT NULL,
    FECHAFABRICACION  DATE,
    IDDETALLEPRODUCTO INT         NOT NULL,
    IDUSUARIO         INT         NOT NULL,
    VIGENCIA          BIT         NOT NULL,

    CONSTRAINT PK_LOTE PRIMARY KEY (IDLOTE),
    CONSTRAINT UQ_LOTE_NROLOTE UNIQUE (NROLOTE),
    CONSTRAINT FK_LOTE_DETALLEPRODUCTO
        FOREIGN KEY (IDDETALLEPRODUCTO) REFERENCES DETALLE_PRODUCTO(IDDETALLEPRODUCTO),
    CONSTRAINT FK_LOTE_USUARIO
        FOREIGN KEY (IDUSUARIO)         REFERENCES USUARIO(IDUSUARIO),
    CONSTRAINT CK_LOTE_STOCK_ACTUAL
        CHECK (STOCK_ACTUAL >= 0),
    CONSTRAINT CK_LOTE_STOCK_INICIAL
        CHECK (STOCK_INICIAL >= 0)
)
GO

CREATE TABLE DETALLE_VENTA (
    IDDETALLEPRODUCTO INT           NOT NULL,
    IDPEDIDO          INT           NOT NULL,
    IDLOTE            INT           NOT NULL,
    PRECIO            DECIMAL(10,2) NOT NULL,
    CANTIDAD          INT           NOT NULL,

    CONSTRAINT PK_DETALLE_VENTA PRIMARY KEY (IDDETALLEPRODUCTO, IDPEDIDO, IDLOTE),
    CONSTRAINT FK_DVENTA_DETALLEPRODUCTO
        FOREIGN KEY (IDDETALLEPRODUCTO) REFERENCES DETALLE_PRODUCTO(IDDETALLEPRODUCTO),
    CONSTRAINT FK_DVENTA_VENTA
        FOREIGN KEY (IDPEDIDO)          REFERENCES VENTA(IDPEDIDO),
    CONSTRAINT FK_DVENTA_LOTE
        FOREIGN KEY (IDLOTE)            REFERENCES LOTE(IDLOTE),
    CONSTRAINT CK_DVENTA_CANTIDAD
        CHECK (CANTIDAD > 0),
    CONSTRAINT CK_DVENTA_PRECIO
        CHECK (PRECIO > 0)
)
GO

CREATE TABLE COMPROBANTEVENTA (
    IDCOMPROBANTE  INT         IDENTITY(1,1) NOT NULL,
    IDPEDIDO       INT         NOT NULL,
    TIPO           VARCHAR(20) NOT NULL,
    NROCOMPROBANTE VARCHAR(20) NOT NULL,
    ESTADO         BIT         NOT NULL,

    CONSTRAINT PK_COMPROBANTEVENTA   PRIMARY KEY (IDCOMPROBANTE),
    CONSTRAINT UQ_COMPROBANTE_NRO    UNIQUE (NROCOMPROBANTE),
    CONSTRAINT FK_COMPROBANTE_VENTA
        FOREIGN KEY (IDPEDIDO) REFERENCES VENTA(IDPEDIDO),
    CONSTRAINT CK_COMPROBANTE_TIPO
        CHECK (TIPO IN ('Boleta', 'Factura'))
)
GO

-- =============================================================
-- TRIGGER ACTUALIZADO: TR_DESCONTAR_STOCK
-- =============================================================
CREATE OR ALTER TRIGGER TR_DESCONTAR_STOCK
ON DETALLE_VENTA
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (
        SELECT 1
        FROM INSERTED I
        INNER JOIN DETALLE_PRODUCTO DP ON I.IDDETALLEPRODUCTO = DP.IDDETALLEPRODUCTO
        WHERE DP.STOCK < I.CANTIDAD
    )
    BEGIN
        RAISERROR('Stock global insuficiente para uno o más productos de la venta.', 16, 1);
        ROLLBACK TRANSACTION;
        RETURN;
    END

    IF EXISTS (
        SELECT 1
        FROM INSERTED I
        INNER JOIN LOTE L ON I.IDLOTE = L.IDLOTE
        WHERE L.STOCK_ACTUAL < I.CANTIDAD
    )
    BEGIN
        RAISERROR('Stock insuficiente en el lote seleccionado.', 16, 1);
        ROLLBACK TRANSACTION;
        RETURN;
    END

    UPDATE DP
    SET DP.STOCK = DP.STOCK - I.CANTIDAD
    FROM DETALLE_PRODUCTO DP
    INNER JOIN INSERTED I ON DP.IDDETALLEPRODUCTO = I.IDDETALLEPRODUCTO;

    UPDATE L
    SET L.STOCK_ACTUAL = L.STOCK_ACTUAL - I.CANTIDAD
    FROM LOTE L
    INNER JOIN INSERTED I ON L.IDLOTE = I.IDLOTE;
END
GO

-- =============================================================
-- SECCIÓN 4: MÓDULO DEVOLUCIONES Y CAMBIOS
-- =============================================================

CREATE TABLE DEVOLUCION (
    IDDEVOLUCION   INT         IDENTITY(1,1) NOT NULL,
    IDPEDIDO       INT         NOT NULL,
    FECHASOLICITUD DATETIME    NOT NULL DEFAULT GETDATE(),
    MOTIVO         VARCHAR(30) NOT NULL,
    OBSERVACION    VARCHAR(300),
    RESULTADO      VARCHAR(15) NOT NULL DEFAULT 'Pendiente',
    IDUSUARIO      INT         NOT NULL,

    CONSTRAINT PK_DEVOLUCION         PRIMARY KEY (IDDEVOLUCION),
    CONSTRAINT UQ_DEVOLUCION_PEDIDO  UNIQUE (IDPEDIDO),
    CONSTRAINT FK_DEVOLUCION_VENTA
        FOREIGN KEY (IDPEDIDO)   REFERENCES VENTA(IDPEDIDO),
    CONSTRAINT FK_DEVOLUCION_USUARIO
        FOREIGN KEY (IDUSUARIO)  REFERENCES USUARIO(IDUSUARIO),
    CONSTRAINT CK_DEVOLUCION_MOTIVO CHECK (MOTIVO IN (
        'Error de despacho',
        'Producto defectuoso',
        'Producto vencido'
    )),
    CONSTRAINT CK_DEVOLUCION_RESULTADO CHECK (RESULTADO IN (
        'Pendiente',
        'Cambio',
        'Reembolso',
        'Rechazado'
    ))
)
GO

CREATE TABLE NOTA_CREDITO (
    IDNOTACREDITO   INT           IDENTITY(1,1) NOT NULL,
    NRONOTA         VARCHAR(20)   NOT NULL,
    IDDEVOLUCION    INT           NOT NULL,
    FECHAEMISION    DATETIME      NOT NULL DEFAULT GETDATE(),
    MONTO           DECIMAL(10,2) NOT NULL,
    TIPO_RESOLUCION VARCHAR(15)   NOT NULL,

    CONSTRAINT PK_NOTA_CREDITO            PRIMARY KEY (IDNOTACREDITO),
    CONSTRAINT UQ_NOTA_CREDITO_NRO        UNIQUE (NRONOTA),
    CONSTRAINT UQ_NOTA_CREDITO_DEVOLUCION UNIQUE (IDDEVOLUCION),
    CONSTRAINT FK_NOTA_CREDITO_DEVOLUCION
        FOREIGN KEY (IDDEVOLUCION) REFERENCES DEVOLUCION(IDDEVOLUCION),
    CONSTRAINT CK_NOTA_CREDITO_MONTO
        CHECK (MONTO > 0),
    CONSTRAINT CK_NOTA_CREDITO_TIPO
        CHECK (TIPO_RESOLUCION IN ('Cambio', 'Reembolso'))
)
GO

CREATE TABLE CAMBIO_PRODUCTO (
    IDCAMBIO         INT           IDENTITY(1,1) NOT NULL,
    IDNOTACREDITO    INT           NOT NULL,
    IDPEDIDO_NUEVO   INT           NOT NULL,
    FECHACAMBIO      DATETIME      NOT NULL DEFAULT GETDATE(),
    MONTO_DIFERENCIA DECIMAL(10,2) NOT NULL DEFAULT 0,
    IDUSUARIO        INT           NOT NULL,

    CONSTRAINT PK_CAMBIO_PRODUCTO    PRIMARY KEY (IDCAMBIO),
    CONSTRAINT UQ_CAMBIO_NOTA        UNIQUE (IDNOTACREDITO),
    CONSTRAINT FK_CAMBIO_NOTA
        FOREIGN KEY (IDNOTACREDITO)  REFERENCES NOTA_CREDITO(IDNOTACREDITO),
    CONSTRAINT FK_CAMBIO_VENTA_NUEVA
        FOREIGN KEY (IDPEDIDO_NUEVO) REFERENCES VENTA(IDPEDIDO),
    CONSTRAINT FK_CAMBIO_USUARIO
        FOREIGN KEY (IDUSUARIO)      REFERENCES USUARIO(IDUSUARIO),
    CONSTRAINT CK_CAMBIO_DIFERENCIA
        CHECK (MONTO_DIFERENCIA >= 0)
)
GO

CREATE TABLE DETALLE_CAMBIO (
    IDDETALLECAMBIO   INT           IDENTITY(1,1) NOT NULL,
    IDCAMBIO          INT           NOT NULL,
    IDDETALLEPRODUCTO INT           NOT NULL,
    CANTIDAD          INT           NOT NULL,
    PRECIOUNITARIO    DECIMAL(10,2) NOT NULL,

    CONSTRAINT PK_DETALLE_CAMBIO      PRIMARY KEY (IDDETALLECAMBIO),
    CONSTRAINT UQ_DETALLE_CAMBIO
        UNIQUE (IDCAMBIO, IDDETALLEPRODUCTO),
    CONSTRAINT FK_DETCAMBIO_CAMBIO
        FOREIGN KEY (IDCAMBIO)          REFERENCES CAMBIO_PRODUCTO(IDCAMBIO),
    CONSTRAINT FK_DETCAMBIO_PRODUCTO
        FOREIGN KEY (IDDETALLEPRODUCTO) REFERENCES DETALLE_PRODUCTO(IDDETALLEPRODUCTO),
    CONSTRAINT CK_DETCAMBIO_CANTIDAD
        CHECK (CANTIDAD > 0),
    CONSTRAINT CK_DETCAMBIO_PRECIO
        CHECK (PRECIOUNITARIO > 0)
)
GO

CREATE OR ALTER TRIGGER TR_DESCONTAR_STOCK_CAMBIO
ON DETALLE_CAMBIO
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (
        SELECT 1
        FROM INSERTED I
        INNER JOIN DETALLE_PRODUCTO DP ON I.IDDETALLEPRODUCTO = DP.IDDETALLEPRODUCTO
        WHERE DP.STOCK < I.CANTIDAD
    )
    BEGIN
        RAISERROR('Stock insuficiente para el producto de reemplazo en el cambio.', 16, 1);
        ROLLBACK TRANSACTION;
        RETURN;
    END

    UPDATE DP
    SET DP.STOCK = DP.STOCK - I.CANTIDAD
    FROM DETALLE_PRODUCTO DP
    INNER JOIN INSERTED I ON DP.IDDETALLEPRODUCTO = I.IDDETALLEPRODUCTO;
END
GO

-- =============================================================
-- SECCIÓN 5: MÓDULO ABASTECIMIENTO
-- =============================================================

CREATE TABLE PROVEEDOR (
    IDPROVEEDOR     INT           IDENTITY(1,1) NOT NULL,
    RUC             CHAR(11)      NOT NULL,
    RAZONSOCIAL     VARCHAR(150)  NOT NULL,
    NOMBRECOMERCIAL VARCHAR(150),
    DIRECCION       VARCHAR(200),
    TELEFONO        CHAR(9),
    CORREO          VARCHAR(100),
    PAGINAWEB       VARCHAR(100),
    CONDICIONPAGO   VARCHAR(50),
    ESTADO          BIT           NOT NULL DEFAULT 1,
    FECHAREGISTRO   DATE          NOT NULL DEFAULT GETDATE(),

    CONSTRAINT PK_PROVEEDOR         PRIMARY KEY (IDPROVEEDOR),
    CONSTRAINT UQ_PROVEEDOR_RUC     UNIQUE (RUC),
    CONSTRAINT CK_PROVEEDOR_RUC     CHECK (LEN(RUC) = 11),
    CONSTRAINT CK_PROVEEDOR_CONDICION CHECK (
        CONDICIONPAGO IN (
            'Contado', 'Credito 15 dias', 'Credito 30 dias',
            'Credito 45 dias', 'Credito 60 dias'
        ) OR CONDICIONPAGO IS NULL
    )
)
GO

CREATE TABLE CONTACTO_PROVEEDOR (
    IDCONTACTO  INT          IDENTITY(1,1) NOT NULL,
    IDPROVEEDOR INT          NOT NULL,
    NOMBRES     VARCHAR(100) NOT NULL,
    CARGO       VARCHAR(80),
    TELEFONO    CHAR(9),
    CELULAR     CHAR(9),
    CORREO      VARCHAR(100),
    PRINCIPAL   BIT          NOT NULL DEFAULT 0,

    CONSTRAINT PK_CONTACTO_PROVEEDOR PRIMARY KEY (IDCONTACTO),
    CONSTRAINT FK_CONTACTO_PROVEEDOR
        FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDOR(IDPROVEEDOR)
)
GO

CREATE UNIQUE INDEX UQ_CONTACTO_PRINCIPAL
ON CONTACTO_PROVEEDOR (IDPROVEEDOR)
WHERE PRINCIPAL = 1
GO

CREATE TABLE ORDEN_COMPRA (
    IDORDEN       INT           IDENTITY(1,1) NOT NULL,
    NROORDEN      VARCHAR(20)   NOT NULL,
    FECHAEMISION  DATE          NOT NULL DEFAULT GETDATE(),
    FECHAESPERADA DATE,
    ESTADO        VARCHAR(20)   NOT NULL DEFAULT 'Pendiente',
    OBSERVACION   VARCHAR(300),
    SUBTOTAL      DECIMAL(12,2) NOT NULL DEFAULT 0,
    IGV           DECIMAL(12,2) NOT NULL DEFAULT 0,
    TOTAL         DECIMAL(12,2) NOT NULL DEFAULT 0,
    IDPROVEEDOR   INT           NOT NULL,
    IDUSUARIO     INT           NOT NULL,

    CONSTRAINT PK_ORDEN_COMPRA    PRIMARY KEY (IDORDEN),
    CONSTRAINT UQ_ORDEN_NROORDEN  UNIQUE (NROORDEN),
    CONSTRAINT FK_ORDEN_PROVEEDOR
        FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDOR(IDPROVEEDOR),
    CONSTRAINT FK_ORDEN_USUARIO
        FOREIGN KEY (IDUSUARIO)   REFERENCES USUARIO(IDUSUARIO),
    CONSTRAINT CK_ORDEN_ESTADO CHECK (
        ESTADO IN ('Pendiente', 'Aprobada', 'Recibida', 'Recibida parcial', 'Anulada')
    ),
    CONSTRAINT CK_ORDEN_FECHAS CHECK (
        FECHAESPERADA IS NULL OR FECHAESPERADA >= FECHAEMISION
    )
)
GO

CREATE TABLE DETALLE_ORDEN_COMPRA (
    IDDETALLEORDEN    INT           IDENTITY(1,1) NOT NULL,
    IDORDEN           INT           NOT NULL,
    IDDETALLEPRODUCTO INT           NOT NULL,
    CANTIDADPEDIDA    INT           NOT NULL,
    CANTIDADRECIBIDA  INT           NOT NULL DEFAULT 0,
    PRECIOUNITARIO    DECIMAL(10,2) NOT NULL,
    SUBTOTAL          AS (CANTIDADPEDIDA * PRECIOUNITARIO),

    CONSTRAINT PK_DETALLE_ORDEN PRIMARY KEY (IDDETALLEORDEN),
    CONSTRAINT FK_DORDEN_ORDEN
        FOREIGN KEY (IDORDEN)           REFERENCES ORDEN_COMPRA(IDORDEN),
    CONSTRAINT FK_DORDEN_DETPRODUCTO
        FOREIGN KEY (IDDETALLEPRODUCTO) REFERENCES DETALLE_PRODUCTO(IDDETALLEPRODUCTO),
    CONSTRAINT UQ_DORDEN_PRODUCTO
        UNIQUE (IDORDEN, IDDETALLEPRODUCTO),
    CONSTRAINT CK_DORDEN_CANTIDAD
        CHECK (CANTIDADPEDIDA > 0),
    CONSTRAINT CK_DORDEN_PRECIO
        CHECK (PRECIOUNITARIO > 0),
    CONSTRAINT CK_DORDEN_RECIBIDA
        CHECK (CANTIDADRECIBIDA >= 0 AND CANTIDADRECIBIDA <= CANTIDADPEDIDA)
)
GO

CREATE OR ALTER TRIGGER TR_ACTUALIZAR_TOTALES_OC
ON DETALLE_ORDEN_COMPRA
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @IGV_RATE DECIMAL(5,4) = 0.18;

    UPDATE OC
    SET
        SUBTOTAL = ISNULL(T.SUMA, 0),
        IGV      = ISNULL(T.SUMA, 0) * @IGV_RATE,
        TOTAL    = ISNULL(T.SUMA, 0) * (1 + @IGV_RATE)
    FROM ORDEN_COMPRA OC
    INNER JOIN (
        SELECT IDORDEN, SUM(CANTIDADPEDIDA * PRECIOUNITARIO) AS SUMA
        FROM DETALLE_ORDEN_COMPRA
        GROUP BY IDORDEN
    ) T ON OC.IDORDEN = T.IDORDEN
    WHERE OC.IDORDEN IN (
        SELECT DISTINCT IDORDEN FROM INSERTED
        UNION
        SELECT DISTINCT IDORDEN FROM DELETED
    );
END
GO

CREATE TABLE RECEPCION_COMPRA (
    IDRECEPCION    INT         IDENTITY(1,1) NOT NULL,
    IDORDEN        INT         NOT NULL,
    NRORECEPCION   VARCHAR(20) NOT NULL,
    FECHARECEPCION DATETIME    NOT NULL DEFAULT GETDATE(),
    NROFACTURA     VARCHAR(30),
    OBSERVACION    VARCHAR(300),
    ESTADO         VARCHAR(20) NOT NULL DEFAULT 'Completa',
    IDUSUARIO      INT         NOT NULL,

    CONSTRAINT PK_RECEPCION      PRIMARY KEY (IDRECEPCION),
    CONSTRAINT UQ_RECEPCION_NRO  UNIQUE (NRORECEPCION),
    CONSTRAINT FK_RECEPCION_ORDEN
        FOREIGN KEY (IDORDEN)   REFERENCES ORDEN_COMPRA(IDORDEN),
    CONSTRAINT FK_RECEPCION_USUARIO
        FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO(IDUSUARIO),
    CONSTRAINT CK_RECEPCION_ESTADO CHECK (
        ESTADO IN ('Completa', 'Parcial', 'Con observacion')
    )
)
GO

CREATE TABLE DETALLE_RECEPCION (
    IDDETRECEPCION   INT           IDENTITY(1,1) NOT NULL,
    IDRECEPCION      INT           NOT NULL,
    IDDETALLEORDEN   INT           NOT NULL,
    CANTIDADRECIBIDA INT           NOT NULL,
    PRECIOCOMPRA     DECIMAL(10,2) NOT NULL,
    IDLOTE           INT NOT NULL,

    CONSTRAINT PK_DETALLE_RECEPCION PRIMARY KEY (IDDETRECEPCION),
    CONSTRAINT FK_DETREC_RECEPCION
        FOREIGN KEY (IDRECEPCION)    REFERENCES RECEPCION_COMPRA(IDRECEPCION),
    CONSTRAINT FK_DETREC_DETORDEN
        FOREIGN KEY (IDDETALLEORDEN) REFERENCES DETALLE_ORDEN_COMPRA(IDDETALLEORDEN),
    CONSTRAINT FK_DETREC_LOTE
        FOREIGN KEY (IDLOTE)         REFERENCES LOTE(IDLOTE),
    CONSTRAINT CK_DETREC_CANTIDAD
        CHECK (CANTIDADRECIBIDA > 0),
    CONSTRAINT CK_DETREC_PRECIO
        CHECK (PRECIOCOMPRA > 0)
)
GO

CREATE OR ALTER TRIGGER TR_AUMENTAR_STOCK_RECEPCION
ON DETALLE_RECEPCION
AFTER INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;

    UPDATE DP
    SET DP.STOCK = DP.STOCK + I.CANTIDADRECIBIDA
    FROM DETALLE_PRODUCTO DP
    INNER JOIN DETALLE_ORDEN_COMPRA DOC ON DP.IDDETALLEPRODUCTO = DOC.IDDETALLEPRODUCTO
    INNER JOIN INSERTED I               ON DOC.IDDETALLEORDEN   = I.IDDETALLEORDEN
    WHERE I.IDLOTE IS NOT NULL;

    UPDATE DOC
    SET DOC.CANTIDADRECIBIDA = DOC.CANTIDADRECIBIDA + I.CANTIDADRECIBIDA
    FROM DETALLE_ORDEN_COMPRA DOC
    INNER JOIN INSERTED I ON DOC.IDDETALLEORDEN = I.IDDETALLEORDEN
    WHERE I.IDLOTE IS NOT NULL;
END
GO

-- =============================================================
-- SECCIÓN 6: VISTAS
-- =============================================================

CREATE OR ALTER VIEW VW_DEVOLUCIONES AS
SELECT
    D.IDDEVOLUCION,
    D.FECHASOLICITUD,
    D.MOTIVO,
    D.RESULTADO,
    D.OBSERVACION,
    V.IDPEDIDO                                                 AS NRO_VENTA,
    V.FECHAHORA                                                AS FECHA_VENTA,
    DATEDIFF(HOUR, V.FECHAHORA, D.FECHASOLICITUD)              AS HORAS_TRANSCURRIDAS,
    ISNULL(C.NOMBRES + ' ' + C.APELLIDOPATERNO, C.RAZONSOCIAL) AS CLIENTE,
    C.NRODOC,
    NC.NRONOTA,
    NC.MONTO,
    U.NOMBRE + ' ' + U.APELLIDOPATERNO                         AS ATENDIDO_POR
FROM DEVOLUCION D
INNER JOIN VENTA        V  ON D.IDPEDIDO     = V.IDPEDIDO
INNER JOIN CLIENTE      C  ON V.IDCLIENTE    = C.IDCLIENTE
INNER JOIN USUARIO      U  ON D.IDUSUARIO    = U.IDUSUARIO
LEFT  JOIN NOTA_CREDITO NC ON NC.IDDEVOLUCION = D.IDDEVOLUCION
GO

CREATE OR ALTER VIEW VW_CAMBIOS_REALIZADOS AS
SELECT
    CP.IDCAMBIO,
    CP.FECHACAMBIO,
    NC.NRONOTA,
    NC.MONTO                                                    AS MONTO_NOTA,
    CP.MONTO_DIFERENCIA,
    ISNULL(C.NOMBRES + ' ' + C.APELLIDOPATERNO, C.RAZONSOCIAL)  AS CLIENTE,
    P.NOMBRE                                                    AS PRODUCTO,
    M.NOMBREMARCA                                               AS MARCA,
    DC.CANTIDAD,
    DC.PRECIOUNITARIO,
    DC.CANTIDAD * DC.PRECIOUNITARIO                             AS SUBTOTAL,
    CP.IDPEDIDO_NUEVO                                           AS NUEVA_VENTA,
    U.NOMBRE + ' ' + U.APELLIDOPATERNO                          AS ATENDIDO_POR
FROM CAMBIO_PRODUCTO    CP
INNER JOIN DETALLE_CAMBIO   DC  ON CP.IDCAMBIO          = DC.IDCAMBIO
INNER JOIN NOTA_CREDITO     NC  ON CP.IDNOTACREDITO     = NC.IDNOTACREDITO
INNER JOIN DEVOLUCION       D   ON NC.IDDEVOLUCION      = D.IDDEVOLUCION
INNER JOIN VENTA            V   ON D.IDPEDIDO           = V.IDPEDIDO
INNER JOIN CLIENTE          C   ON V.IDCLIENTE          = C.IDCLIENTE
INNER JOIN DETALLE_PRODUCTO DP  ON DC.IDDETALLEPRODUCTO = DP.IDDETALLEPRODUCTO
INNER JOIN PRODUCTO         P   ON DP.IDPRODUCTO        = P.IDPRODUCTO
INNER JOIN MARCA            M   ON DP.IDMARCA           = M.IDMARCA
INNER JOIN USUARIO          U   ON CP.IDUSUARIO         = U.IDUSUARIO
GO

CREATE OR ALTER VIEW VW_ORDENES_COMPRA AS
SELECT
    OC.IDORDEN,
    OC.NROORDEN,
    OC.FECHAEMISION,
    OC.FECHAESPERADA,
    OC.ESTADO,
    P.RAZONSOCIAL   AS PROVEEDOR,
    P.CONDICIONPAGO,
    U.NOMBRE + ' ' + U.APELLIDOPATERNO AS GENERADOPOR,
    OC.SUBTOTAL,
    OC.IGV,
    OC.TOTAL,
    OC.OBSERVACION
FROM ORDEN_COMPRA OC
INNER JOIN PROVEEDOR P ON OC.IDPROVEEDOR = P.IDPROVEEDOR
INNER JOIN USUARIO   U ON OC.IDUSUARIO   = U.IDUSUARIO
GO

-- Vista actualizada con DP.CANTIDAD y DP.UNIDAD en lugar de PRESENTACION
CREATE OR ALTER VIEW VW_DETALLE_ORDENES AS
SELECT
    OC.NROORDEN,
    OC.ESTADO                                                AS ESTADO_ORDEN,
    P.NOMBRE                                                 AS PRODUCTO,
    M.NOMBREMARCA                                            AS MARCA,
    PR2.TIPOPRESENTACION + ' x ' +
        CAST(DP.CANTIDAD AS VARCHAR) + ' ' + DP.UNIDAD       AS PRESENTACION,
    DOC.CANTIDADPEDIDA,
    DOC.CANTIDADRECIBIDA,
    DOC.CANTIDADPEDIDA - DOC.CANTIDADRECIBIDA                AS PENDIENTE,
    DOC.PRECIOUNITARIO,
    DOC.SUBTOTAL
FROM DETALLE_ORDEN_COMPRA DOC
INNER JOIN ORDEN_COMPRA     OC   ON DOC.IDORDEN           = OC.IDORDEN
INNER JOIN DETALLE_PRODUCTO DP   ON DOC.IDDETALLEPRODUCTO = DP.IDDETALLEPRODUCTO
INNER JOIN PRODUCTO         P    ON DP.IDPRODUCTO         = P.IDPRODUCTO
INNER JOIN MARCA            M    ON DP.IDMARCA            = M.IDMARCA
INNER JOIN PRESENTACION     PR2  ON DP.IDPRESENTACION     = PR2.IDPRESENTACION
GO

CREATE OR ALTER VIEW VW_PROVEEDORES AS
SELECT
    P.IDPROVEEDOR,
    P.RUC,
    P.RAZONSOCIAL,
    P.NOMBRECOMERCIAL,
    P.CONDICIONPAGO,
    P.TELEFONO              AS TEL_EMPRESA,
    CP.NOMBRES              AS CONTACTO_PRINCIPAL,
    CP.CARGO,
    CP.CELULAR              AS CEL_CONTACTO,
    CP.CORREO               AS CORREO_CONTACTO
FROM PROVEEDOR P
LEFT JOIN CONTACTO_PROVEEDOR CP
       ON P.IDPROVEEDOR = CP.IDPROVEEDOR AND CP.PRINCIPAL = 1
WHERE P.ESTADO = 1
GO

-- Vista actualizada con DP.CANTIDAD y DP.UNIDAD
CREATE OR ALTER VIEW VW_LOTES_POR_VENCER AS
SELECT
    L.IDLOTE,
    L.NROLOTE,
    L.FECHAVENCIMIENTO,
    DATEDIFF(DAY, GETDATE(), L.FECHAVENCIMIENTO) AS DIAS_RESTANTES,
    L.STOCK_ACTUAL,
    P.NOMBRE                                     AS PRODUCTO,
    M.NOMBREMARCA                                AS MARCA,
    PR.TIPOPRESENTACION + ' x ' +
        CAST(DP.CANTIDAD AS VARCHAR) + ' ' + DP.UNIDAD AS PRESENTACION
FROM LOTE L
INNER JOIN DETALLE_PRODUCTO DP ON L.IDDETALLEPRODUCTO = DP.IDDETALLEPRODUCTO
INNER JOIN PRODUCTO         P  ON DP.IDPRODUCTO       = P.IDPRODUCTO
INNER JOIN MARCA            M  ON DP.IDMARCA          = M.IDMARCA
INNER JOIN PRESENTACION     PR ON DP.IDPRESENTACION   = PR.IDPRESENTACION
WHERE L.VIGENCIA = 1
  AND L.FECHAVENCIMIENTO <= DATEADD(DAY, 90, GETDATE())
  AND L.STOCK_ACTUAL > 0
GO

-- =============================================================
-- SECCIÓN 7: DATOS DE PRUEBA
-- =============================================================

INSERT INTO USUARIO (
    DNI, NOMBRE, APELLIDOPATERNO, APELLIDOMATERNO,
    CORREO, TELEFONO, FECHANACIMIENTO, DIRECCION,
    SEXO, CARGO, USUARIO, CLAVE, ESTADO, PREGUNTA, RESPUESTA
)
VALUES
('72345678', 'Juan Carlos', 'Perez',    'Gonzales',
 'jperez@gmail.com',    '987654321', '1985-05-15',
 'Av. Balta 123, Chiclayo',          'M', 'Administrador',
 'admin',     '1234',         1, '¿Nombre de tu primera mascota?', 'Bobby'),

('73456789', 'Maria Elena', 'Torres',   'Mendoza',
 'mtorres@gmail.com',   '987654322', '1990-08-22',
 'Calle Real 456, Chiclayo',         'F', 'Vendedor',
 'mtorres',   'ventas2026',   1, '¿Ciudad de nacimiento?',         'Chiclayo'),

('74567890', 'Luis Miguel', 'Ramirez',  'Vargas',
 'lramirez@gmail.com',  '987654323', '1992-11-03',
 'Av. Salaverry 789, Chiclayo',      'M', 'Vendedor',
 'lramirez',  'seguro456',    1, '¿Color favorito?',               'Azul'),

('75678901', 'Ana Lucia',   'Castillo', 'Rojas',
 'acastillo@gmail.com', '987654324', '1988-01-18',
 'Urb. Santa Victoria Mz A, Chiclayo','F', 'Cajero',
 'acastillo', 'caja789',      1, '¿Mejor amiga de la infancia?',   'Carla'),

('76789012', 'Carlos',      'Guevara',  'Soto',
 'cguevara@gmail.com',  '987654325', '1995-07-30',
 'Paseo Las Musas 102, Chiclayo',    'M', 'Almacenero',
 'cguevara',  'almacen000',   1, '¿Comida favorita?',              'Arroz con pato')
GO

INSERT INTO PROVEEDOR (
    RUC, RAZONSOCIAL, NOMBRECOMERCIAL, DIRECCION,
    TELEFONO, CORREO, CONDICIONPAGO, ESTADO
)
VALUES
('20100055888', 'LABORATORIOS PORTUGAL S.A.C.',       'Lab Portugal',
 'Av. Industrial 456, Lima',      '014512233',
 'ventas@labportugal.com.pe',     'Credito 30 dias', 1),

('20512345678', 'DROGUERIA MEDIFARMA S.A.',             'Medifarma',
 'Jr. Comercio 789, Lima',        '014523344',
 'pedidos@medifarma.pe',          'Contado',         1),

('20609876543', 'DISTRIBUIDORA INKA PHARMA E.I.R.L.',  'Inka Pharma',
 'Calle Los Pinos 102, Chiclayo', '074201122',
 'inkapharmachl@gmail.com',       'Credito 15 dias', 1)
GO

INSERT INTO CONTACTO_PROVEEDOR (
    IDPROVEEDOR, NOMBRES, CARGO, CELULAR, CORREO, PRINCIPAL
)
VALUES
(1, 'Roberto Llontop', 'Representante de ventas', '987001122',
    'rllontop@labportugal.com.pe',  1),
(1, 'Carmen Davila',   'Logistica',               '987003344',
    'cdavila@labportugal.com.pe',   0),
(2, 'Jorge Huaman',    'Ejecutivo de cuenta',     '987005566',
    'jhuaman@medifarma.pe',         1),
(3, 'Lucia Farro',     'Administradora',          '987007788',
    'lfarro@inkapharmachl.com',     1)
GO

INSERT INTO ORDEN_COMPRA (
    NROORDEN, FECHAEMISION, FECHAESPERADA, ESTADO,
    OBSERVACION, IDPROVEEDOR, IDUSUARIO
)
VALUES
('OC-2026-001', '2026-05-01', '2026-05-10', 'Recibida',
 'Primera orden del mes de mayo',   1, 5),
('OC-2026-002', '2026-05-10', '2026-05-20', 'Pendiente',
 'Reposicion de antibioticos',      2, 5),
('OC-2026-003', '2026-05-15', '2026-05-25', 'Aprobada',
 'Productos de alta rotacion',      3, 5)
GO



-- =============================================================
-- 1. PRESENTACION (Catálogo limpio de empaques)
-- =============================================================
INSERT INTO PRESENTACION (TIPOPRESENTACION, ESTADO)
VALUES 
('Caja', 1),
('Blíster', 1),
('Frasco', 1),
('Tubo', 1),
('Ampolla', 1)
GO

-- =============================================================
-- 2. LABORATORIO
-- =============================================================
INSERT INTO LABORATORIO (NOMBRELABORATORIO, DIRECCION, TELEFONO, VIGENCIA)
VALUES 
('Bayer S.A.', 'Av. Paseo de la República 3074, Lima', '014561234', 1),
('Farmindustria S.A.', 'Av. Cesar Vallejo 500, Lima', '012345678', 1),
('Genfar', 'Calle Los Frutales 220, Lima', '013456789', 1),
('Teva Perú', 'Av. Venezuela 1000, Lima', '015678901', 1),
('AC Farma', 'Av. Separadora Industrial 123, Lima', '016789012', 1)
GO

-- =============================================================
-- 3. MARCA (Asociado a su respectivo Laboratorio)
-- =============================================================
INSERT INTO MARCA (NOMBREMARCA, DESCRIPCION, VIGENCIA, IDLABORATORIO)
VALUES 
('Aspirina', 'Analgésico y antipirético tradicional', 1, 1),           -- De Bayer
('Apronax', 'Antiinflamatorio para dolores fuertes', 1, 1),            -- De Bayer
('Doloflam', 'Relajante muscular y analgésico', 1, 2),                 -- De Farmindustria
('Ibuprofeno Genfar', 'Genérico antiinflamatorio', 1, 3),              -- De Genfar
('Salbutamol Teva', 'Inhalador broncodilatador', 1, 4)                 -- De Teva
GO

-- =============================================================
-- 4. PRODUCTO (El principio activo o nombre genérico)
-- =============================================================
INSERT INTO PRODUCTO (NOMBRE, ESTADO, DESCRIPCION)
VALUES 
('Ácido Acetilsalicílico 100mg', 1, 'Prevención de riesgos cardiovasculares'),
('Naproxeno Sódico 550mg', 1, 'Tratamiento sintomático del dolor agudo'),
('Meloxicam 15mg', 1, 'Alivio de los síntomas de la artritis'),
('Ibuprofeno 400mg', 1, 'Tratamiento del dolor leve a moderado y fiebre'),
('Salbutamol Inhalador 100mcg', 1, 'Alivio del broncoespasmo en asma')
GO

-- =============================================================
-- 5. DETALLE_PRODUCTO (El SKU vendible que une todo)
-- ESTADO ahora es BIT (1 = Activo)
-- =============================================================
INSERT INTO DETALLE_PRODUCTO (SKU, PRECIO, ESTADO, STOCK, CANTIDAD, UNIDAD, IDMARCA, IDPRESENTACION, IDPRODUCTO)
VALUES 
-- 1: Aspirina en Caja de 100
('SKU-00001', 45.00, 1, 20, 100, 'Tabletas', 1, 1, 1), 

-- 2: Aspirina en Blíster de 10 (Mismo producto/marca, distinta presentación y cantidad)
('SKU-00002', 5.00, 1, 50, 10, 'Tabletas', 1, 2, 1),   

-- 3: Ibuprofeno Genfar en Caja de 100
('SKU-00003', 25.00, 1, 15, 100, 'Tabletas', 4, 1, 4), 

-- 4: Ibuprofeno Genfar en Blíster de 10
('SKU-00004', 3.00, 1, 80, 10, 'Tabletas', 4, 2, 4),   

-- 5: Salbutamol Inhalador Frasco (1 Unidad)
('SKU-00005', 22.50, 1, 10, 1, 'Unidad', 5, 3, 5)      
GO

-- =============================================================
-- 6. CLIENTE (Naturales y Jurídicos)
-- =============================================================
INSERT INTO CLIENTE (TIPODOC, NRODOC, TIPO_CLIENTE, NOMBRES, APELLIDOPATERNO, APELLIDOMATERNO, RAZONSOCIAL, DIRECCION, TELEFONO, CORREO)
VALUES 
('DNI', '70112233', 'Natural', 'Jose', 'Luis', 'Rojas', NULL, 'Av. Principal 123, Cayalti', '999111222', 'jose.rojas@email.com'),
('DNI', '70223344', 'Natural', 'Maria', 'Gomez', 'Perez', NULL, 'Calle Los Pinos 456, Chiclayo', '999222333', 'maria.gomez@email.com'),
('DNI', '70334455', 'Natural', 'Carlos', 'Sanchez', 'Ruiz', NULL, 'Urb. Santa Victoria Mz B, Lambayeque', '999333444', 'carlos.sanchez@email.com'),
('RUC', '20123456789', 'Juridico', NULL, NULL, NULL, 'BOTICA EL PUEBLO S.A.C.', 'Av. Balta 789, Chiclayo', '074223344', 'compras@boticaelpueblo.com'),
('RUC', '20987654321', 'Juridico', NULL, NULL, NULL, 'CLINICA SAN JUAN EIRL', 'Av. Salaverry 1000, Chiclayo', '074556677', 'logistica@clinicasanjuan.pe')
GO

-- =============================================================
-- 7. MEDIO_PAGO
-- =============================================================
INSERT INTO MEDIO_PAGO (NOMBRE, ESTADO)
VALUES 
('Efectivo', 1),
('Tarjeta Visa', 1),
('Tarjeta Mastercard', 1),
('Yape', 1),
('Plin', 1)
GO

-- =============================================================
-- 2. DETALLE ORDEN COMPRA
-- =============================================================
INSERT INTO DETALLE_ORDEN_COMPRA (
    IDORDEN, IDDETALLEPRODUCTO,
    CANTIDADPEDIDA, PRECIOUNITARIO
)
VALUES
(1, 1, 50, 40.00),
(1, 2, 100, 4.00),
(2, 3, 80, 20.00),
(2, 4, 150, 2.50),
(3, 5, 30, 18.00)
GO

INSERT INTO RECEPCION_COMPRA (
    IDORDEN, NRORECEPCION,
    FECHARECEPCION, NROFACTURA,
    OBSERVACION, ESTADO, IDUSUARIO
)
VALUES
(1, 'RC-2026-001', GETDATE(), 'F001-1001',
 'Recepción completa de Aspirina', 'Completa', 5),

(1, 'RC-2026-002', GETDATE(), 'F001-1002',
 'Recepción parcial blíster', 'Parcial', 5),

(2, 'RC-2026-003', GETDATE(), 'F001-1003',
 'Recepción Ibuprofeno', 'Completa', 5),

(2, 'RC-2026-004', GETDATE(), 'F001-1004',
 'Recepción parcial Genfar', 'Parcial', 5),

(3, 'RC-2026-005', GETDATE(), 'F001-1005',
 'Recepción Salbutamol', 'Completa', 5)
GO

INSERT INTO LOTE (
    NROLOTE, FECHAVENCIMIENTO, STOCK_INICIAL,
    STOCK_ACTUAL, FECHAFABRICACION,
    IDDETALLEPRODUCTO, IDUSUARIO, VIGENCIA
)
VALUES
('LOT-2026-001', '2027-01-15', 100, 100, '2025-12-01', 1, 5, 1),
('LOT-2026-002', '2027-02-10', 200, 200, '2025-12-15', 2, 5, 1),
('LOT-2026-003', '2026-11-20', 150, 150, '2025-11-10', 3, 5, 1),
('LOT-2026-004', '2026-12-30', 300, 300, '2025-12-05', 4, 5, 1),
('LOT-2026-005', '2027-03-05', 80, 80, '2025-12-20', 5, 5, 1)
GO

-- =============================================================
-- 4. DETALLE RECEPCION
-- =============================================================
INSERT INTO DETALLE_RECEPCION (
    IDRECEPCION, IDDETALLEORDEN,
    CANTIDADRECIBIDA, PRECIOCOMPRA, IDLOTE
)
VALUES
(1, 1, 50, 38.00, 1),
(2, 2, 70, 3.50, 2),
(3, 3, 80, 18.50, 3),
(4, 4, 120, 2.20, 4),
(5, 5, 30, 16.00, 5)
GO

-- =============================================================
-- 5. VENTAS
-- =============================================================
INSERT INTO VENTA (
    FECHAHORA, ESTADO,
    IDUSUARIO, IDCLIENTE, IDMEDIOPAGO
)
VALUES
(GETDATE(), 1, 2, 1, 1),
(GETDATE(), 1, 2, 2, 2),
(GETDATE(), 1, 3, 3, 4),
(GETDATE(), 1, 4, 4, 1),
(GETDATE(), 1, 3, 5, 5)
GO

-- =============================================================
-- 6. DETALLE VENTA
-- =============================================================
INSERT INTO DETALLE_VENTA (
    IDDETALLEPRODUCTO,
    IDPEDIDO,
    IDLOTE,
    PRECIO,
    CANTIDAD
)
VALUES
(1, 1, 1, 45.00, 2),
(2, 2, 2, 5.00, 5),
(3, 3, 3, 25.00, 3),
(4, 4, 4, 3.00, 10),
(5, 5, 5, 22.50, 1)
GO

-- =============================================================
-- 7. COMPROBANTE VENTA
-- =============================================================
INSERT INTO COMPROBANTEVENTA (
    IDPEDIDO, TIPO,
    NROCOMPROBANTE, ESTADO
)
VALUES
(1, 'Boleta',  'B001-000001', 1),
(2, 'Boleta',  'B001-000002', 1),
(3, 'Factura', 'F001-000001', 1),
(4, 'Boleta',  'B001-000003', 1),
(5, 'Factura', 'F001-000002', 1)
GO

-- =============================================================
-- 8. DEVOLUCIONES
-- =============================================================
INSERT INTO DEVOLUCION (
    IDPEDIDO,
    FECHASOLICITUD,
    MOTIVO,
    OBSERVACION,
    RESULTADO,
    IDUSUARIO
)
VALUES
(1, GETDATE(), 'Producto defectuoso',
 'Caja dañada', 'Cambio', 2),

(2, GETDATE(), 'Error de despacho',
 'Producto incorrecto', 'Reembolso', 2),

(3, GETDATE(), 'Producto vencido',
 'Fecha próxima a vencer', 'Pendiente', 3),

(4, GETDATE(), 'Producto defectuoso',
 'Blister abierto', 'Cambio', 4),

(5, GETDATE(), 'Error de despacho',
 'Cantidad errónea', 'Rechazado', 3)
GO

-- =============================================================
-- 9. NOTAS DE CREDITO
-- =============================================================
INSERT INTO NOTA_CREDITO (
    NRONOTA,
    IDDEVOLUCION,
    MONTO,
    TIPO_RESOLUCION
)
VALUES
('NC-000001', 1, 90.00, 'Cambio'),
('NC-000002', 2, 25.00, 'Reembolso'),
('NC-000003', 3, 75.00, 'Cambio'),
('NC-000004', 4, 30.00, 'Cambio'),
('NC-000005', 5, 22.50, 'Reembolso')
GO

-- =============================================================
-- 10. CAMBIO PRODUCTO
-- =============================================================
INSERT INTO CAMBIO_PRODUCTO (
    IDNOTACREDITO,
    IDPEDIDO_NUEVO,
    MONTO_DIFERENCIA,
    IDUSUARIO
)
VALUES
(1, 2, 0, 2),
(2, 3, 10, 2),
(3, 4, 5, 3),
(4, 5, 0, 4),
(5, 1, 2.50, 3)
GO

-- =============================================================
-- 11. DETALLE CAMBIO
-- =============================================================
INSERT INTO DETALLE_CAMBIO (
    IDCAMBIO,
    IDDETALLEPRODUCTO,
    CANTIDAD,
    PRECIOUNITARIO
)
VALUES
(1, 1, 1, 45.00),
(2, 2, 2, 5.00),
(3, 3, 1, 25.00),
(4, 4, 3, 3.00),
(5, 5, 1, 22.50)
GO

PRINT '============================================================'
PRINT ' BDFarmacia v2.1 - Script completo ejecutado correctamente.'
PRINT ' Ajustes integrados: Presentacion limpia, Cantidad/Unidad en SKU'
PRINT '============================================================'
GO